chore(ctb): Make l1FeeVault var immutable.
ethereum-optimism/optimism-audit-fixes pull request #3
Opened 2022-07-29 14:55 UTC by maurelian

This also addresses an 'unitialized variable' slither finding.

2022-08-09 21:55 UTC, tynes commented on packages/contracts-bedrock/contracts/L2/SequencerFeeVault.sol
> -    constructor() Semver(0, 0, 1) {}
Could you make this a constructor arg? I'm taking a new approach with rewriting the state surgery stuff in go where I deploy the L2 predeploys to geth's evm because parsing the compiler out in go is a mega pain. Will need to walk the ast to find all the offsets and it would take me awhile to implement all of that. I'll be sure to implement double checks in go for the immutables

2022-08-09 21:55 UTC, tynes requested changes
See other comment

2022-08-10 17:46 UTC, maurelian commented on packages/contracts-bedrock/contracts/L2/SequencerFeeVault.sol
> -    constructor() Semver(0, 0, 1) {}
I'll give that a shot... what would it look like, this?

```
constructor() {
  Semver.constructor(0, 0, 1);
}
```

2022-09-16 19:20 UTC, maurelian commented
Not a priority, closing.

2022-09-16 19:20 UTC, closed without merging